//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamDoAnhTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class history
    {
        public int ID { get; set; }
        public int CustomerId { get; set; }
        public Nullable<System.DateTime> Ngaydongtien { get; set; }
        public string Detail { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> status { get; set; }
        public Nullable<int> loanid { get; set; }
        public string CustomerCode { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
