//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CamDoAnhTu.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public System.DateTime Date { get; set; }
        public string IDCus { get; set; }
        public int ID { get; set; }
        public int Status { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
